dist: trusty
sudo: required

language: scala

scala:
  - 2.11.11

jdk:
  - oraclejdk8

matrix:
  fast_finish: true
#  allow_failures:
#    - jdk: oraclejdk8

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
  - wget https://archive.apache.org/dist/thrift/0.10.0/thrift-0.10.0.tar.gz
  - tar xfz thrift-0.10.0.tar.gz
  - cd thrift-0.10.0
  - ./configure --disable-plugin --disable-tutorial --disable-tests --disable-coverage --without-c_glib --without-erlang --without-nodejs --without-php --without-python --without-ruby --without-go
  - sudo make install
  - cd -

script:
  - sbt clean coverage test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls
